__1.__ Решить систему уравнений методом Крамера:

   а) $\begin{cases}
x_{1}-2x_{2}=1 \\
3x_{1}-4x_{2}=7
\end{cases}$
    
   б) $\begin{cases}
2x_{1}-x_{2}+5x_{3}=10 \\
x_{1}+x_{2}-3x_{3}=-2 \\
2x_{1}+4x_{2}+x_{3}=1
\end{cases}$

In [1]:
import numpy as np

In [25]:
a = np.array([[1, -2], [3, -4]])
detA = np.linalg.det(a)
print(f'Определитель detA = {detA:.0f}')
a1 = np.array([[1, -2], [7, -4]])
detA1 = np.linalg.det(a1)
print(f'Определитель detA1 = {detA1:.0f}')
a2 = np.array([[1, 1], [3, 7]])
detA2 = np.linalg.det(a2)
print(f'Определитель detA2 = {detA2:.0f}')
print(f'x1 = {(detA1/detA):.0f}')
print(f'x2 = {(detA2/detA):.0f}')

Определитель detA = 2
Определитель detA1 = 10
Определитель detA2 = 4
x1 = 5
x2 = 2


In [10]:
a = np.array([[2, -1, 5], [1, 1, -3],[2, 4, 1]])
detA = np.linalg.det(a)
print(f'Определитель detA = {detA:.0f}')
a1 = np.array([[10, -1, 5], [-2, 1, -3],[1, 4, 1]])
detA1 = np.linalg.det(a1)
print(f'Определитель detA1 = {detA1:.0f}')
a2 = np.array([[2, 10, 5], [1, -2, -3],[2, 1, 1]])
detA2 = np.linalg.det(a2)
print(f'Определитель detA2 = {detA2:.0f}')
a3 = np.array([[2, -1, 10], [1, 1, -2],[2, 4, 1]])
detA3 = np.linalg.det(a2)
print(f'Определитель detA3 = {detA3:.0f}')
print(f'x1 = {(detA1/detA):.0f}')
print(f'x2 = {(detA2/detA):.0f}')
print(f'x3 = {(detA3/detA):.0f}')

Определитель detA = 43
Определитель detA1 = 86
Определитель detA2 = -43
Определитель detA3 = -43
x1 = 2
x2 = -1
x3 = -1


__2.__ Найти $L$-матрицу $LU$-разложения для матрицы коэффициентов:

   а)$$\begin{pmatrix}
1 & 2 & 4 \\ 
2 & 9 & 12 \\ 
3 & 26 & 30
\end{pmatrix}$$
    
   б)$$\begin{pmatrix}
1 & 1 & 2 & 4\\ 
2 & 5 & 8 & 9\\ 
3 & 18 & 29 & 18\\
4 & 22 & 53 & 33
\end{pmatrix}$$

а)$$\begin{pmatrix}
1 & 2 & 4 \\ 
2 & 9 & 12 \\ 
3 & 26 & 30
\end{pmatrix}$$

$$\begin{pmatrix}
1 & 2 & 4 \\ 
0 & 5 & 4 \\ 
0 & 20 & 18
\end{pmatrix}$$

U = \begin{pmatrix}
1 & 2 & 4 \\ 
0 & 5 & 4 \\ 
0 & 0 & 2
\end{pmatrix}
L = \begin{pmatrix}
1 & 0 & 0 \\ 
2 & 1 & 0 \\ 
3 & 4 & 1
\end{pmatrix}

б)$$\begin{pmatrix}
1 & 1 & 2 & 4\\ 
2 & 5 & 8 & 9\\ 
3 & 18 & 29 & 18\\
4 & 22 & 53 & 33
\end{pmatrix}$$

$$\begin{pmatrix}
1 & 1 & 2 & 4\\ 
0 & 3 & 4 & 1\\ 
0 & 15 & 23 & 6\\
0 & 18 & 45 & 27
\end{pmatrix}$$

$$\begin{pmatrix}
1 & 1 & 2 & 4\\ 
0 & 3 & 4 & 1\\ 
0 & 0 & 3 & 1\\
0 & 0 & 21 & 21
\end{pmatrix}$$

U = $$\begin{pmatrix}
1 & 1 & 2 & 4\\ 
0 & 3 & 4 & 1\\ 
0 & 0 & 3 & 1\\
0 & 0 & 0 & 14
\end{pmatrix}$$
L = $$\begin{pmatrix}
1 & 0 & 0 & 0\\ 
2 & 1 & 0 & 0\\ 
3 & 5 & 1 & 0\\
4 & 6 & 7 & 1
\end{pmatrix}$$

__3.__ Решить систему линейных уравнений методом $LU$-разложения

$$\begin{cases}
2x_{1}+x_{2}+3x_{3}=1 \\
11x_{1}+7x_{2}+5x_{3}=-6 \\
9x_{1}+8x_{2}+4x_{3}=-5
\end{cases}$$

In [27]:
import pprint
import scipy
import scipy.linalg
import numpy as np

In [36]:
A = scipy.array([ [2, 1, 3], [11, 7, 5], [9, 8, 4] ])
b =  scipy.array([1, -6, -5])
P, L, U = scipy.linalg.lu(A)
print ('P:')
pprint.pprint(P)
print ('L:')
pprint.pprint(L)
print ('U:')
pprint.pprint(U)

P:
array([[0., 0., 1.],
       [1., 0., 0.],
       [0., 1., 0.]])
L:
array([[ 1.        ,  0.        ,  0.        ],
       [ 0.81818182,  1.        ,  0.        ],
       [ 0.18181818, -0.12      ,  1.        ]])
U:
array([[11.        ,  7.        ,  5.        ],
       [ 0.        ,  2.27272727, -0.09090909],
       [ 0.        ,  0.        ,  2.08      ]])


In [37]:
y = np.linalg.solve(L, b)
print(y)

[ 1.         -6.81818182 -6.        ]


In [38]:
x = np.linalg.solve(U, y)
print(x)

[ 3.38461538 -3.11538462 -2.88461538]


__4.__ Решить систему линейных уравнений методом Холецкого

$$\begin{cases}
81x_{1}-45x_{2}+45x_{3}=531 \\
-45x_{1}+50x_{2}-15x_{3}=-460 \\
45x_{1}-15x_{2}+38x_{3}=193
\end{cases}$$

In [21]:
A = scipy.array([ [81, -45, 45], [-45, 50, -15], [45, -15, 38] ])
P, L, U = scipy.linalg.lu(A)
print ('P:')
pprint.pprint(P)
print ('L:')
pprint.pprint(L)
print ('U:')
pprint.pprint(U)

P:
array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])
L:
array([[ 1.        ,  0.        ,  0.        ],
       [-0.55555556,  1.        ,  0.        ],
       [ 0.55555556,  0.4       ,  1.        ]])
U:
array([[ 81., -45.,  45.],
       [  0.,  25.,  10.],
       [  0.,   0.,   9.]])


In [34]:
from numpy.linalg import cholesky
A = scipy.array([ [81, -45, 45], [-45, 50, -15], [45, -15, 38] ])
b = scipy.array([531, -460, 193])
L = cholesky(A)
print ('L:')
pprint.pprint(L)
print ('LT:')
pprint.pprint(L.T)

L:
array([[ 9.,  0.,  0.],
       [-5.,  5.,  0.],
       [ 5.,  2.,  3.]])
LT:
array([[ 9., -5.,  5.],
       [ 0.,  5.,  2.],
       [ 0.,  0.,  3.]])


In [32]:
y = np.linalg.solve(L, b)
print(y)

[ 59. -33. -12.]


In [35]:
x = np.linalg.solve(L.T, y)
print(x)

[ 6. -5. -4.]
